const nodemailer = require('nodemailer');

const sendLeadEmail = async (leadDetails) => {
  const { name, mobileNumber, emailAddress, serviceCategory, message } = leadDetails;
  
  // Use environment variables if provided, otherwise fallback to an Ethereal mock account
  let transporter;

  if (process.env.SMTP_USER && process.env.SMTP_PASS) {
    transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT) || 465,
      secure: process.env.SMTP_SECURE !== 'false', // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    });
  } else {
    // Generate test SMTP service from ethereal.email for development
    try {
      const testAccount = await nodemailer.createTestAccount();
      transporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false,
        auth: {
          user: testAccount.user,
          pass: testAccount.pass
        }
      });
      console.log('Using Ethereal Mailer fallback. No SMTP credentials found in .env');
    } catch (err) {
      console.error('Failed to create Ethereal mail account, emailing disabled:', err);
      return;
    }
  }

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 12px; background-color: #ffffff;">
      <h2 style="color: #0d9488; border-bottom: 2px solid #0d9488; padding-bottom: 10px; margin-top: 0;">New Service Lead Received!</h2>
      <p style="font-size: 14px; color: #555555;">You have received a new inquiry from the Global Service Point website.</p>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #333333; width: 140px;">Customer Name:</td>
          <td style="padding: 8px 0; color: #555555;">${name}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #333333;">Mobile Number:</td>
          <td style="padding: 8px 0; color: #0d9488; font-weight: bold;">${mobileNumber}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #333333;">Email Address:</td>
          <td style="padding: 8px 0; color: #555555;">${emailAddress || 'Not Provided'}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #333333;">Service Category:</td>
          <td style="padding: 8px 0; color: #555555;"><span style="background-color: #f3f4f6; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold;">${serviceCategory}</span></td>
        </tr>
      </table>
      
      <div style="margin-top: 20px; padding: 15px; background-color: #f9fafb; border-left: 4px solid #0d9488; border-radius: 4px;">
        <h4 style="margin: 0 0 8px 0; color: #333333;">Customer Message:</h4>
        <p style="margin: 0; font-size: 14px; color: #555555; line-height: 1.5; font-style: italic;">"${message}"</p>
      </div>

      <p style="font-size: 11px; color: #888888; margin-top: 25px; border-t: 1px solid #eeeeee; padding-top: 15px;">
        This email was auto-generated by Global Service Point Lead Engine.
      </p>
    </div>
  `;

  try {
    const info = await transporter.sendMail({
      from: `"Global Service Point" <${process.env.SMTP_USER || 'leads@globalservicepoint.com'}>`,
      to: 'sujayyoativ@gmail.com',
      subject: `🚨 New Lead: ${name} (${serviceCategory})`,
      html: htmlContent
    });

    console.log(`[EMAIL DISPATCHED] Message Sent! MessageId: ${info.messageId}`);
    // Ethereal helper url
    const previewUrl = nodemailer.getTestMessageUrl(info);
    if (previewUrl) {
      console.log(`[EMAIL PREVIEW LINK] View mock email draft at: ${previewUrl}`);
    }
  } catch (error) {
    console.error('Error dispatching lead email notification:', error);
  }
};

module.exports = { sendLeadEmail };
